apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 labels:
    component: stolon-keeper
    stolon-cluster: default-postgres
 name: default-postgres-data-default-postgres-keeper-0
 namespace: <REPLACE_WITH_NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: <REPLACE_WITH_STORAGE_CLASS_NAME> 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 labels:
    component: stolon-keeper
    stolon-cluster: default-postgres
 name: default-postgres-data-default-postgres-keeper-0
 namespace: <REPLACE_WITH_NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: <REPLACE_WITH_STORAGE_CLASS_NAME> 
