apiVersion: v1    
kind: PersistentVolumeClaim
metadata:  
  name: temp-pvc-0
  namespace: <REPLACE_WITH_NAMESPACE>
spec:
  storageClassName: <REPLACE_WITH_STORAGE_CLASS_NAME>
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: <REPLACE_WITH_STORAGE_SIZE>
