apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 labels:
    component: stolon-keeper
    stolon-cluster: soar-postgres
 name: soar-postgres-data-soar-postgres-keeper-0
 namespace: <REPLACE_WITH_NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: <REPLACE_WITH_STORAGE_CLASS_NAME> 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 labels:
    component: stolon-keeper
    stolon-cluster: soar-postgres
 name: soar-postgres-data-soar-postgres-keeper-1
 namespace: <REPLACE_WITH_NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: <REPLACE_WITH_STORAGE_CLASS_NAME> 
